## Numeric Python
- Calculations element wise

### Arrays
 - Contains only one data type 

In [1]:
import numpy as np
from IPython.display import Image
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

In [13]:
np_baseball = np.array(baseball)
print(type(np_baseball))

<class 'numpy.ndarray'>


#### Creating random arrays
- 1D: np.random.rand(7)
- 2D: np.random.rand(2,4). This creates 2-dimensional numpy arrays of lenght 2 in dimension 0 with lenght 4 in dimension -1 meaning 4 values per array
- 3D: np.random.rand(4,2,3). This creates 4 arrays, with 2 subarrays and 3 values per subarray

In [16]:
height = np.array(np.random.rand(8))
height

array([0.24648564, 0.44506857, 0.95371113, 0.14005472, 0.72895241,
       0.16910712, 0.91788273, 0.47832743])

In [10]:
height_m = height * 2.2
height_m[:25]

array([1.96048511, 0.20056865, 1.66992945, 1.38793438, 0.40188431,
       1.48183215, 1.13375152, 1.7647355 , 0.9544658 , 1.24098629,
       1.20888599, 0.23336974, 1.17923258, 1.55265909, 0.24571432,
       0.72071148, 1.28234246, 1.13461497, 1.71227419, 1.06025691,
       0.33594526, 0.54597068, 2.19275882, 2.00491025, 2.10993572])

In [6]:
np.array([4, 3, 0]) + np.array([0, 2, 2])

array([4, 5, 2])

In [12]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [2]:
#2d array
np_2d = np.array([[180, 215, 210, 210, 188, 176, 209, 200], 
                 [0.24648564, 0.44506857, 0.95371113, 0.14005472, 0.72895241,
       0.16910712, 0.91788273, 0.47832743]])
np_2d

array([[1.8000000e+02, 2.1500000e+02, 2.1000000e+02, 2.1000000e+02,
        1.8800000e+02, 1.7600000e+02, 2.0900000e+02, 2.0000000e+02],
       [2.4648564e-01, 4.4506857e-01, 9.5371113e-01, 1.4005472e-01,
        7.2895241e-01, 1.6910712e-01, 9.1788273e-01, 4.7832743e-01]])

- Methods have brackets after them
- Attributes do not have brackets

For shape of the arrays is (2,8) meaning 2 rows and 8 columns. Or 2 arrays with 8 values each.


In [5]:
np_2d.shape, type(np_2d) #ndarray means n dimensionsional array

((2, 8), numpy.ndarray)

### Subsetting arrays
The indexes before the comma refer to the rows, while those after the comma refer to the columns. The : is for slicing; in this example, it tells Python to include all rows. np_array[:, 3:5]

In [10]:
np_2d[1][-1], np_2d[0][2], np_2d[1, -1]

(0.47832743, 210.0, 0.47832743)

In [11]:
# Iwant all rows and only a subset of columns
np_2d[:, 3:5]

array([[2.1000000e+02, 1.8800000e+02],
       [1.4005472e-01, 7.2895241e-01]])

In [12]:
np_2d[1, :] # I want everything from row one 

array([0.24648564, 0.44506857, 0.95371113, 0.14005472, 0.72895241,
       0.16910712, 0.91788273, 0.47832743])

In [14]:
np_baseball

array([180, 215, 210, 210, 188, 176, 209, 200])

In [ ]:
# # Print out the 50th row of np_baseball
# print(np_baseball[49, :])

# # Select the entire second column of np_baseball: np_weight_lb
# np_weight_lb = np_baseball[:,1]

# # Print out height of 124th player
# print(np_baseball[123,0])

In [ ]:
# np_baseball = np.array(baseball)

# # Print out addition of np_baseball and updated
# print(np_baseball + updated)

# # Create numpy array: conversion
# conversion = np.array([0.0254,0.453592,1])

# # Print out product of np_baseball and conversion
# print(np_baseball * conversion)

### Numpy statistics

In [ ]:

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

In [ ]:
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height
med = np.median(np_baseball[:, 0])
print("Median: " + str(med))

# Print out the standard deviation on height
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column
corr = np.corrcoef(np_baseball[:,0], np_baseball[:, 1])
print("Correlation: " + str(corr))